services:
- type: web
  name: saas-backend
  env: node
  plan: starter
  buildCommand: npm ci && npx prisma generate && npm run build
  startCommand: npm start
  autoDeploy: true
  envVars:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: 10000
  - key: APP_URL
    fromService:
      type: web
      name: saas-backend
      property: url
  - key: DATABASE_URL
    fromDatabase:
      name: saas-db
      property: connectionString
  - key: JWT_SECRET
    sync: false
  - key: SMTP_HOST
    sync: false
  - key: SMTP_PORT
    sync: false
  - key: SMTP_USER
    sync: false
  - key: SMTP_PASS
    sync: false
  - key: SMTP_FROM
    sync: false
  - key: STRIPE_SECRET_KEY
    sync: false
  - key: STRIPE_WEBHOOK_SECRET
    sync: false
  - key: STRIPE_PRICE_ID
    sync: false
  - key: STRIPE_SUCCESS_URL
    sync: false
  - key: STRIPE_CANCEL_URL
    sync: false

databases:
- name: saas-db
  plan: starter